Optimize Events and Clean up
Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io pull request #107
Opened 2022-10-14 07:12 UTC by minhngo3818

This PR addresses following issues:
    - Compact all event component files into 1 to reduce multiple imports from node modules whenever calling many components
    - Split events css one located in pages folder for events page file, and the other one is for event components 
    - Update file extension

2022-10-19 23:19 UTC, KHVBui requested changes
It looks like the last commit, "Merge branch 'main' into minhngo-events-optimize-cleanup" restored the event components in `pages/events/components` you meant to delete in earlier commits.

I recommend deleting them as well as the folder to avoid redundancy.

2022-10-19 23:21 UTC, KHVBui reviewed
BTW does compacting the event component files into 1 file result in speed increases? If so, by how much? It would be nice to see a quantified result for the change.

2022-10-22 04:41 UTC, minhngo3818 commented
I will fix the merge branch issue.

I'm not certain about how much speed will increase, but it will. Compacting components in one file will help the system to find those from only one directory. It also prevents redundancy from importing same dependencies multiple time in run-time by calling different event components. The problem will happen if we use separate files to store each components. We just need to import once to use all.

2022-10-25 21:08 UTC, KHVBui approved these changes

2022-10-26 06:34 UTC, merged