Controller Framework
Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io pull request #115
Opened 2022-11-14 02:05 UTC by minhngo3818

Express JS has a nature of minimalistic that allows programmers to have the freedom to handle routing logic. However, it could result in redundancy in which multiple data models share the same routing logic. This framework will generalize routing logic for most of the data models of the club website. 

This PR will: 
- Edit the name of the database in the console log
- Add a skeleton of the framework which will be addressed in upcoming issues. Separate tasks to implement each member function of the framework will be posted in GitHub issues

2022-11-15 23:07 UTC, jameslindfors requested changes
Really great work it made it really easy to add a new route. 

Needs revision:
- Use the try/catch or .then().catch() method rather than mongoose callback

2022-11-18 08:12 UTC, minhngo3818 commented on backend/framework/controller.js
> +            .limit(50)
the issue is addressed in #117 for building a pagination feature

2022-11-18 20:09 UTC, jameslindfors approved these changes

2022-11-18 20:10 UTC, jameslindfors commented
Tested the changes and everything is working well. You're all set to merge. 👍

2022-11-19 07:12 UTC, merged