tutorial component and restyle
Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io pull request #142
Opened 2023-04-11 04:54 UTC by 777Prabhjot

Hey, i have made tutorial section as you told please check it out.

2023-04-12 03:43 UTC, 777Prabhjot commented
@minhngo3818 done please check now

2023-04-16 17:23 UTC, minhngo3818 commented on client/src/components/resources/resources.css
> +	font-size: min(4vw, 1.3rem);
can you make it bold for the title font weight?

2023-04-16 17:42 UTC, minhngo3818 commented on client/src/components/resources/resources.css
> +	padding: 0px 5px;
I think the padding should be 2px 8px to make space loosen.

2023-04-16 17:47 UTC, minhngo3818 commented on client/src/components/resources/resources.css
> +	border-radius: 2px;
The border weight is thinner than the design but I think yours fit better making the view not too focused on tags. I think the border-radius should be increased to 5px. It looks like a sharp rectangle with 2px.

2023-04-16 17:50 UTC, minhngo3818 commented on client/src/pages/resources/Resources.jsx
> +import Tutorial from "../../components/resources/tutorials";
keep the plural name

2023-04-16 17:50 UTC, minhngo3818 commented on client/src/pages/resources/Resources.jsx
> +					<Tutorial />
keep the plural name

2023-04-16 17:50 UTC, minhngo3818 commented on client/src/components/resources/tutorials.jsx
> +function Tutorial() {
The component name should be plural because we render multiple tutorial items.

2023-04-16 18:00 UTC, minhngo3818 reviewed
There are some trivial stylings that need fixing.`ToggleItem` is a good approach since we can reuse it for reading and organization items. The reading schema is quite different from the other two. See issue #66. If you think it's possible, can you make the `ToggleItem` a separate component and make it more general to apply for tutorial, reading, and organization items? Otherwise, I will make a separate issue or leave all three to have their own component. Please let me know.

2023-04-17 12:30 UTC, 777Prabhjot commented
@minhngo3818 done

2023-04-19 18:41 UTC, minhngo3818 requested changes
Make sure to remove the comment.
Excellent!

2023-04-19 18:41 UTC, minhngo3818 commented on client/src/pages/resources/Resources.jsx
> +// import Tutorials from "./Tutorials";
Please remove this line

2023-04-20 09:34 UTC, 777Prabhjot commented on client/src/pages/resources/Resources.jsx
> +// import Tutorials from "./Tutorials";
removed

2023-04-25 01:45 UTC, minhngo3818 approved these changes

2023-04-25 01:45 UTC, merged

2023-04-25 01:53 UTC, minhngo3818 commented
Solved #128