same sized dropdown boxes
Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io pull request #60
Opened 2022-08-27 22:31 UTC by DanielZavala11

2022-08-27 22:31 UTC, DanielZavala11 commented
issue #18 conform with feedback

2022-08-27 23:42 UTC, KHVBui requested changes
While you're working on the navbar, could you also fix the console error on line 59 in "NavigationBar.js"?
```
Warning: Received `false` for a non-boolean attribute `className`.
If you used to conditionally omit it with className={condition && value}, pass className={condition ? value : undefined} instead.
```

Otherwise it all looks good!

2022-08-27 23:42 UTC, KHVBui commented on src/navbar/navbar.css
> +}
Add a return here at the end of the file.

2022-08-27 23:46 UTC, KHVBui commented
Also don't forget to format your project with prettier so that it can successfully build.

2022-08-29 04:58 UTC, KHVBui approved these changes
Good to go!

2022-08-29 04:59 UTC, merged