Add contact us section to homepage
Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io pull request #73
Opened 2022-09-06 06:05 UTC by minhngo3818

Add "Contact Us" section to homepage. Responsive feature was included.

Solved #54 

Demo 
![Screenshot 2022-09-05 230256](https://user-images.githubusercontent.com/78233689/188558624-0d3b7077-5ca6-4745-9721-2d9f4c003de4.png)

2022-09-06 06:45 UTC, KHVBui requested changes
We should also probably have a conversation about design choices later because "About Us" and "Contact Us" aren't consistent stylistically right now. We don't need to do that for this PR though.

2022-09-06 06:45 UTC, KHVBui commented on client/src/pages/home/components/contact-us/ContactUs.js
> +					We care about your oppinion!
typo on "oppinion"

2022-09-06 06:45 UTC, KHVBui commented on client/src/pages/home/components/contact-us/contact-us.css
> +}
Looks too indented on the left on smaller screen size.

Recommend adjusting padding like the About Us section.

<img width="710" alt="Screen Shot 2022-09-05 at 11 41 23 PM" src="https://user-images.githubusercontent.com/36748732/188564694-c28148d2-0acc-463d-9a8b-f6154555b001.png">

2022-09-07 17:10 UTC, KHVBui approved these changes
Good to go!

2022-09-07 17:24 UTC, minhngo3818 commented
I just added more space between picture and text.

2022-09-07 17:51 UTC, KHVBui approved these changes

2022-09-07 20:45 UTC, merged